### PR TITLE
Removed "settings" word & Added Google +1

### PR DESCRIPTION
**Pull request by insign**
- Removed "settings" word from every tab since already in a setting page
   - before: http://d.pr/i/gccV
   - after: http://d.pr/i/ARNP
- Added Google +1 in "social" tab
   - (remains add in the default theme)
   - (remains better interface options)
   - in another pull I added the jquery code (ok, will try to use git in my editor)

### CODE REVIEW

**Comment by insign** [comment]
Very happy :)

**Comment by apptamin** [comment]
I don't see the G+ button showing in the app stage. Have you added that, too?

**Comment by insign** [comment]
Oh, sorry. But for now, you need insert it manually in appstage.php, like:

<?php if ( of_get_option( 'apptamin_pobutton_showhidden_checkbox' ) ) { ?>

```
<script type="text/javascript">
  (function() {
    var po = document.createElement('script');
    po.type = 'text/javascript';
    po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(po, s);
  })();
</script>

<div class="po-button">
```

 <?php
 if ( of_get_option( 'apptamin_pocustom_url_text' ) ) {
   $po_link = of_get_option( 'apptamin_pocustom_url_text' );
 } else {
   $po_link = get_bloginfo( 'url' );
 }
 ?>
      <div class="g-plusone" data-size="tall" href="<?php echo $po_link;
?>"></div>
    </div>
  <?php } ?>

**Comment by apptamin** [comment]
No worries. Maybe we should change the admin text then.

2012/12/26 insign notifications@github.com

**Pull request merged**
